services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pdadmin4@gmail.com}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
          PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
          - pgadmin:/root/.pgadmin
      ports:
          - "5050:80"
      networks:
          - postgres
      restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

#  eureka-server:
#    image: essejacquesdansomon/server-eureka:local
#    container_name: eureka-server
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
#    networks:
#      - spring
#    ports:
#      - "8761:8761"
#    depends_on:
#      - zipkin
#
#  apigateway:
#    image: essejacquesdansomon/apigw:local
#    container_name: apigateway-server
#    ports:
#      - "8060:8060"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SERVER_PORT=8060
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server

  customer:
    image: essejacquesdansomon/customer:local
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq

  fraud:
    image: essejacquesdansomon/fraud:local
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq

  notification:
    image: essejacquesdansomon/notification:local
    container_name: notification
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
    postgres:
    pgadmin:
