spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG